/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import kordinator.Kordinator;

/**
 *
 * @author Aca
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        lblUlogovani = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuClanovi = new javax.swing.JMenu();
        miPrikaziClanove = new javax.swing.JMenuItem();
        miDodajClana = new javax.swing.JMenuItem();
        menuTreneri = new javax.swing.JMenu();
        miPrikaziTrenere = new javax.swing.JMenuItem();
        miDodajTrenera = new javax.swing.JMenuItem();
        menuEvidencije = new javax.swing.JMenu();
        miPrikaziEvidencije = new javax.swing.JMenuItem();
        dodajEvidenciju = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ulogovani trener:");

        lblUlogovani.setText("Ime Prezime");

        menuClanovi.setText("Clanovi teretane");

        miPrikaziClanove.setText("prikazi");
        miPrikaziClanove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPrikaziClanoveActionPerformed(evt);
            }
        });
        menuClanovi.add(miPrikaziClanove);

        miDodajClana.setText("dodaj");
        miDodajClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDodajClanaActionPerformed(evt);
            }
        });
        menuClanovi.add(miDodajClana);

        jMenuBar1.add(menuClanovi);

        menuTreneri.setText("Treneri");

        miPrikaziTrenere.setText("prikazi");
        menuTreneri.add(miPrikaziTrenere);

        miDodajTrenera.setText("dodaj");
        menuTreneri.add(miDodajTrenera);

        jMenuBar1.add(menuTreneri);

        menuEvidencije.setText("Evidencije Treninga");

        miPrikaziEvidencije.setText("prikazi");
        miPrikaziEvidencije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPrikaziEvidencijeActionPerformed(evt);
            }
        });
        menuEvidencije.add(miPrikaziEvidencije);

        dodajEvidenciju.setText("dodaj");
        dodajEvidenciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajEvidencijuActionPerformed(evt);
            }
        });
        menuEvidencije.add(dodajEvidenciju);

        jMenuBar1.add(menuEvidencije);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblUlogovani, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblUlogovani))
                .addContainerGap(240, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miPrikaziClanoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPrikaziClanoveActionPerformed
        Kordinator.getInstance().otvoriPrikazClanovaFormu();
    }//GEN-LAST:event_miPrikaziClanoveActionPerformed

    private void miDodajClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDodajClanaActionPerformed
        Kordinator.getInstance().orvoriFormuDodajClana();
    }//GEN-LAST:event_miDodajClanaActionPerformed

    private void miPrikaziEvidencijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPrikaziEvidencijeActionPerformed
        Kordinator.getInstance().otvoriPrikazEvidencijaFormu();
    }//GEN-LAST:event_miPrikaziEvidencijeActionPerformed

    private void dodajEvidencijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajEvidencijuActionPerformed
        Kordinator.getInstance().otvoriFormuDodajEvidenciju();
    }//GEN-LAST:event_dodajEvidencijuActionPerformed

    /**
     * @return 
     */

    public JLabel getLblUlogovani() {
        return lblUlogovani;
    }
    /**
     * @param lblUlogovani
     */
    public void setLblUlogovani(JLabel lblUlogovani) {
        this.lblUlogovani = lblUlogovani;
    }

    public JMenu getMenuClanovi() {
        return menuClanovi;
    }

    public void setMenuClanovi(JMenu menuClanovi) {
        this.menuClanovi = menuClanovi;
    }

    public JMenu getMenuTreneri() {
        return menuTreneri;
    }

    public void setMenuTreneri(JMenu menuTreneri) {
        this.menuTreneri = menuTreneri;
    }

    public JMenuItem getMiDodajClana() {
        return miDodajClana;
    }

    public void setMiDodajClana(JMenuItem miDodajClana) {
        this.miDodajClana = miDodajClana;
    }

    public JMenuItem getMiDodajTrenera() {
        return miDodajTrenera;
    }

    public void setMiDodajTrenera(JMenuItem miDodajTrenera) {
        this.miDodajTrenera = miDodajTrenera;
    }

    public JMenuItem getMiPrikaziClanove() {
        return miPrikaziClanove;
    }

    public void setMiPrikaziClanove(JMenuItem miPrikaziClanove) {
        this.miPrikaziClanove = miPrikaziClanove;
    }

    public JMenuItem getMiPrikaziTrenere() {
        return miPrikaziTrenere;
    }

    public void setMiPrikaziTrenere(JMenuItem miPrikaziTrenere) {
        this.miPrikaziTrenere = miPrikaziTrenere;
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem dodajEvidenciju;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblUlogovani;
    private javax.swing.JMenu menuClanovi;
    private javax.swing.JMenu menuEvidencije;
    private javax.swing.JMenu menuTreneri;
    private javax.swing.JMenuItem miDodajClana;
    private javax.swing.JMenuItem miDodajTrenera;
    private javax.swing.JMenuItem miPrikaziClanove;
    private javax.swing.JMenuItem miPrikaziEvidencije;
    private javax.swing.JMenuItem miPrikaziTrenere;
    // End of variables declaration//GEN-END:variables
}
